# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQNZk4XUML1GEB4_WdXAstpXg2tOMAd3
"""

from IPython.display import HTML

html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A Letter for You</title>
    <!-- Imports Tailwind CSS for modern styling -->
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- Imports cursive and serif fonts for a classic letter look -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Merriweather:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet">

    <style>
        /* Apply fonts */
        .font-letter {
            font-family: 'Great Vibes', cursive;
        }
        .font-body {
            font-family: 'Merriweather', serif;
        }

        /* Smooth transition for showing/hiding pages */
        .page {
            display: none; /* Hide all pages by default */
            opacity: 0;
            transition: opacity 0.5s ease-in-out;
        }
        .page.active {
            display: block;
            opacity: 1;
        }
    </style>
</head>
<body class="bg-rose-50 min-h-screen flex items-center justify-center p-4 md:p-8 font-body">

    <!-- Main container that looks like a piece of paper -->
    <div class="w-full max-w-2xl bg-white rounded-lg shadow-2xl p-8 md:p-16 relative overflow-hidden">

        <!-- A subtle decorative element -->
        <div class="absolute top-0 left-0 w-full h-2 bg-rose-200"></div>

        <!-- Page 1: The Initial Question -->
        <div id="page1" class="page active text-center">
            <h1 class="font-letter text-5xl md:text-7xl text-rose-700 mb-8">My Shona,</h1>
            <p class="text-lg md:text-xl text-gray-700 leading-relaxed mb-12">
                Last few nights, when the city quiets and my phone stays dark, I still reach for the space where your voice used to be in my Kestopur room, at Ddp house, everywhere. I miss the way you’d read a single line from a poem and pause, letting it settle between us like warm breath on cold glass. I miss the eye rolls you’d give when something annoyed you, and how it could light my whole day from a thousand miles away. Most of all, I miss us—the gentle rhythm we had before I let my distractions drown it out. I see now how often I left you carrying the weight of both our hearts, and I’m learning, slowly and earnestly, to hold you first.
                <br><br>
                I don’t want to forget. I want to remember better. And I believe we both still carry a quiet wish to try. So here’s a small lantern I’d love to light together, if you’re willing :)
            </p>

            <div class="flex flex-col sm:flex-row justify-center gap-4">
                <button onclick="showPage('page2')" class="font-body font-bold bg-green-500 hover:bg-green-600 text-white px-10 py-3 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                    Yes
                </button>
                <button onclick="showPage('page3')" class="font-body font-bold bg-red-500 hover:bg-red-600 text-white px-10 py-3 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                    No
                </button>
            </div>
        </div>

        <!-- Page 2: The "Yes" Message (Elaborate) -->
        <div id="page2" class="page">
            <h2 class="font-letter text-5xl md:text-6xl text-rose-700 mb-8">Thank you...</h2>
            <div class="text-left text-gray-800 text-base md:text-lg leading-loose space-y-6 pr-2">
                <p>
                    One hour each day—only when exams don’t steal your evenings/mornings—your time.
Just sixty minutes on video, the world shrinking to the glow of our screens. We start from scratch, like two travelers meeting at a familiar crossroads, but wiser.
                </p>
                <p>
                    •  Mondays & Thursdays: We take turns reading aloud—one chapter of a book we choose together.
                 <p>
                    •  Tuesdays: We watch a short film or a single episode, pausing to share what it stirs in us—like trading postcards from our inner worlds.
                </p>
                    •  Wednesdays & Sundays: —we each bring one small insight (a place we’d visit, a fear we’re facing, a hope we’re nursing) and listen without fixing, only holding.
                </p>
                    •  Fridays: —we write a single sentence about something the other did that week that felt like love, then read it aloud.
                <p>
                    •  Saturdays: Free choice— could be virtual coffee, sketching the same sunset, or simply sitting in silence until it feels like presence.
                </p>
                <p>
                    No pressure to fill every minute with words. Some nights we might just breathe together and let the quiet mend what silence once broke. The only rule: we show up as we are, and we leave the old neglect outside the door.
                </p>
                <p class="font-bold text-center mt-6">
                    If this feels like a bridge worth crossing, answer with a single word—“yes”—and I’ll send the first book title.
                </p>
            </div>

            <p class="text-center text-lg md:text-xl text-gray-700 mt-12 mb-8">
                If you need time, I’ll wait with the lantern lit. Either way, know that loving you is the clearest truth I carry.
            </p>

            <div class="flex flex-col sm:flex-row justify-center gap-4">
                <button onclick="showPage('page4')" class="font-body font-bold bg-green-500 hover:bg-green-600 text-white px-10 py-3 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                    Yes
                </button>
                <button onclick="showPage('page3')" class="font-body font-bold bg-red-500 hover:bg-red-600 text-white px-10 py-3 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                    No
                </button>
            </div>
        </div>

        <!-- Page 3: The "No" / Error Message -->
        <div id="page3" class="page text-center">
            <h1 class="font-letter text-5xl md:text-7xl text-gray-500 mb-8">Oh...</h1>
            <p class="text-lg md:text-xl text-gray-600 leading-relaxed mb-12">
                I understand.
                <br><br>
                My apologies for bothering you. The message has been respectfully discarded.
            </p>

            <div class="flex justify-center">
                 <button onclick="showPage('page1')" class="font-body font-bold bg-gray-400 hover:bg-gray-500 text-white px-10 py-3 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                    Go Back
                </button>
            </div>
        </div>

        <!-- Page 4: The Final "Yes" Message with External Links -->
        <div id="page4" class="page text-center">
            <h1 class="font-letter text-6xl md:text-8xl text-rose-700 mb-8">You do?!</h1>
            <p class="text-xl md:text-2xl text-gray-800 leading-relaxed">
                You've just made me the happiest person in the entire world.
                <br><br>
                This is just the beginning.
            </p>

            <p class="text-center text-lg md:text-xl text-gray-700 mt-12 mb-8">
                Are you ready for our beginning?
            </p>

            <!-- Buttons that redirect to WhatsApp links -->
            <div class="flex flex-col sm:flex-row justify-center gap-4">
                <button onclick="window.location.href='https://call.whatsapp.com/video/57QiQFFbPXwFTEHBgoTXW4'" class="font-body font-bold bg-green-500 hover:bg-green-600 text-white px-10 py-3 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                    Yess
                </button>
                <button onclick="window.location.href='https://wa.me/919874884292'" class="font-body font-bold bg-red-500 hover:bg-red-600 text-white px-10 py-3 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                    No Sorry
                </button>
            </div>

            <p class="text-xs text-gray-500 mt-4">
                (Note: These buttons will attempt to open WhatsApp outside of this preview environment.)
            </p>
        </div>

    </div>

    <script>
        // Store the currently active page ID
        let currentPage = 'page1';

        function showPage(pageId) {
            // Find the current page element and hide it
            const currentPageElement = document.getElementById(currentPage);
            if (currentPageElement) {
                // Start fade out
                currentPageElement.style.opacity = '0';
                // Wait for the fade out to finish before setting display: none
                setTimeout(() => {
                    currentPageElement.classList.remove('active');
                }, 500); // Matches CSS transition duration
            }

            // Find the new page element and show it
            const newPageElement = document.getElementById(pageId);
            if (newPageElement) {
                // We use a tiny timeout to allow the 'display: none' to apply
                // before adding the 'active' class, which triggers the fade-in.
                setTimeout(() => {
                    newPageElement.classList.add('active');
                    // Ensure opacity is set back to 1 for the transition to work
                    newPageElement.style.opacity = '1';
                }, 100);
            }

            // Update the current page ID
            currentPage = pageId;
        }
    </script>

</body>
</html>
"""

display(HTML(html_content))